In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
%ls

Classification.ipynb  HW4.pdf  PCA.ipynb.ipynb  titanic.xls


In [ ]:
%cd drive/MyDrive/ML_HW4

[Errno 2] No such file or directory: 'drive/MyDrive/ML_HW4'
/content/drive/MyDrive/ML_HW4


## Load data

In [ ]:
#############################################################
#         TODO: read dataset as pandas dataframe            #
#############################################################

df = pd.read_excel('titanic.xls')

In [ ]:
df.head()

pclass  survived                                             name     sex  \
0       1         1                    Allen, Miss. Elisabeth Walton  female   
1       1         1                   Allison, Master. Hudson Trevor    male   
2       1         0                     Allison, Miss. Helen Loraine  female   
3       1         0             Allison, Mr. Hudson Joshua Creighton    male   
4       1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female   

       age  sibsp  parch  ticket      fare    cabin embarked boat   body  \
0  29.0000      0      0   24160  211.3375       B5        S    2    NaN   
1   0.9167      1      2  113781  151.5500  C22 C26        S   11    NaN   
2   2.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   
3  30.0000      1      2  113781  151.5500  C22 C26        S  NaN  135.0   
4  25.0000      1      2  113781  151.5500  C22 C26        S  NaN    NaN   

                         home.dest  
0                     St Louis, MO  
1  Montreal, PQ / Chesterville, ON  
2  Montreal, PQ / Chesterville, ON  
3  Montreal, PQ / Chesterville, ON  
4  Montreal, PQ / Chesterville, ON

In [ ]:
df.shape

(1309, 14)

In [ ]:
df.describe()

pclass     survived          age        sibsp        parch  \
count  1309.000000  1309.000000  1046.000000  1309.000000  1309.000000   
mean      2.294882     0.381971    29.881135     0.498854     0.385027   
std       0.837836     0.486055    14.413500     1.041658     0.865560   
min       1.000000     0.000000     0.166700     0.000000     0.000000   
25%       2.000000     0.000000    21.000000     0.000000     0.000000   
50%       3.000000     0.000000    28.000000     0.000000     0.000000   
75%       3.000000     1.000000    39.000000     1.000000     0.000000   
max       3.000000     1.000000    80.000000     8.000000     9.000000   

              fare        body  
count  1308.000000  121.000000  
mean     33.295479  160.809917  
std      51.758668   97.696922  
min       0.000000    1.000000  
25%       7.895800   72.000000  
50%      14.454200  155.000000  
75%      31.275000  256.000000  
max     512.329200  328.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   pclass     1309 non-null   int64  
 1   survived   1309 non-null   int64  
 2   name       1309 non-null   object 
 3   sex        1309 non-null   object 
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64  
 6   parch      1309 non-null   int64  
 7   ticket     1309 non-null   object 
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object 
 10  embarked   1307 non-null   object 
 11  boat       486 non-null    object 
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object 
dtypes: float64(3), int64(4), object(7)
memory usage: 143.3+ KB


In [ ]:
#############################################################
#            TODO: Convert the dataset to X,y               #
#############################################################

X = df.drop('survived', axis=1)
y = df['survived']

In [ ]:
X.isna().sum()

pclass          0
name            0
sex             0
age           263
sibsp           0
parch           0
ticket          0
fare            1
cabin        1014
embarked        2
boat          823
body         1188
home.dest     564
dtype: int64

## Preprocessing

In [ ]:
########################################################################
#     TODO: Delete columns that are not used or have too many nulls    #
########################################################################

X = X.drop(['name', 'ticket', 'cabin', 'boat', 'body', 'home.dest'], axis=1)

In [ ]:
X.head()

In [ ]:
X.nunique()

pclass        3
sex           2
age          98
sibsp         7
parch         8
fare        281
embarked      3
dtype: int64

In [ ]:
X.isna().sum()

pclass        0
sex           0
age         263
sibsp         0
parch         0
fare          1
embarked      2
dtype: int64

In [ ]:
############################################################################################
#     TODO: Fill in the nulls with the appropriate value, such as median, mean or mode     #
############################################################################################

median_age = X['age'].median()
median_fare = X['fare'].median()

X.fillna({'age': median_age, 'fare': median_fare}, inplace=True)

mode_embarked = X['embarked'].mode()[0]
X['embarked'].fillna(mode_embarked, inplace=True)

In [ ]:
# All columns must not contain null

X.isna().sum()

pclass      0
sex         0
age         0
sibsp       0
parch       0
fare        0
embarked    0
dtype: int64

In [ ]:
X.nunique()

pclass        3
sex           2
age          98
sibsp         7
parch         8
fare        281
embarked      3
dtype: int64

In [ ]:
#############################################################
#    TODO: create Dummy Variable for categorical columns    #
#############################################################

X = pd.get_dummies(X, columns=['sex', 'embarked'], prefix=['is', 'embarked'], drop_first=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   pclass     1309 non-null   int64  
 1   survived   1309 non-null   int64  
 2   name       1309 non-null   object 
 3   sex        1309 non-null   object 
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64  
 6   parch      1309 non-null   int64  
 7   ticket     1309 non-null   object 
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    object 
 10  embarked   1307 non-null   object 
 11  boat       486 non-null    object 
 12  body       121 non-null    float64
 13  home.dest  745 non-null    object 
dtypes: float64(3), int64(4), object(7)
memory usage: 143.3+ KB


In [ ]:
#############################################################
#              TODO: Normalize numeric columns              #
#############################################################
from sklearn.preprocessing import StandardScaler

cols_to_normalize = ['age', 'sibsp', 'parch', 'fare']
scaler = StandardScaler().fit_transform(X[cols_to_normalize])
X[cols_to_normalize] = scaler

In [ ]:
from sklearn.decomposition import PCA

##############################################################
#  TODO: Reduce input dimensions to 5 dimensions using PCA   #
##############################################################

n_components = 5
X_pca = PCA(n_components=n_components).fit_transform(X)
X_pca_df = pd.DataFrame(X_pca, columns=[f"PC{i}" for i in range(1, n_components+1)])

In [ ]:
#############################################################
#              TODO: split to train and test                #
#############################################################

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_pca_df, y, test_size=0.2, random_state=0)

In [ ]:
X_train.shape

(1047, 5)

In [ ]:
X_test.shape

(262, 5)

## Desisiom Tree

In [ ]:
from sklearn import tree
###################################################################
#  TODO: Train the decision tree classifier on the training data  #
###################################################################
clftree = tree.DecisionTreeClassifier(random_state=0)
clftree.fit(X_train, y_train)

DecisionTreeClassifier(random_state=0)

### Predict values using trained model

In [ ]:
#####################################################################
# TODO: Predict the output class for the training and test datasets #
#####################################################################

y_train_pred =  clftree.predict(X_train)
y_test_pred =  clftree.predict(X_test)

### evaluation metrics

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score
#####################################################################
# TODO: Calculate accuracy for training and all metrics for testing #
#####################################################################
train_acc, test_acc, test_precision, test_recall, test_f1_score, test_conf_matrix = [accuracy_score(y_train, y_train_pred),
                                                                                   accuracy_score(y_test, y_test_pred),
                                                                                   precision_score(y_test, y_test_pred),
                                                                                   recall_score(y_test, y_test_pred),
                                                                                   f1_score(y_test, y_test_pred),
                                                                                   confusion_matrix(y_test, y_test_pred)]

print("Training accuracy:", train_acc)
print("Testing accuracy:", test_acc)
print("Testing precision:", test_precision)
print("Testing recall:", test_recall)
print("Testing F1 score:", test_f1_score)
print("Testing confusion matrix:")
print(test_conf_matrix)

Training accuracy: 0.9694364851957975
Testing accuracy: 0.6755725190839694
Testing precision: 0.5903614457831325
Testing recall: 0.49
Testing F1 score: 0.5355191256830601
Testing confusion matrix:
[[128  34]
 [ 51  49]]


## Bagging

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.BaggingClassifier.html

In [ ]:
from sklearn.ensemble import BaggingClassifier
###################################################################
#      TODO: Train the bagging classifier on the training data    #
###################################################################
bag_clf = BaggingClassifier(base_estimator=clftree, n_estimators=100, random_state=0)
bag_clf.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_base.py:166: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(


BaggingClassifier(base_estimator=DecisionTreeClassifier(random_state=0),
                  n_estimators=100, random_state=0)

### Predict values using trained model

In [ ]:
#####################################################################
# TODO: Predict the output class for the training and test datasets #
#####################################################################

y_train_pred =  bag_clf.predict(X_train)
y_test_pred =  bag_clf.predict(X_test)

### evaluation metrics

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score
#####################################################################
# TODO: Calculate accuracy for training and all metrics for testing #
#####################################################################
train_acc, test_acc, test_precision, test_recall, test_f1_score, test_conf_matrix = [accuracy_score(y_train, y_train_pred),
                                                                                   accuracy_score(y_test, y_test_pred),
                                                                                   precision_score(y_test, y_test_pred),
                                                                                   recall_score(y_test, y_test_pred),
                                                                                   f1_score(y_test, y_test_pred),
                                                                                   confusion_matrix(y_test, y_test_pred)]

print("Training accuracy:", train_acc)
print("Testing accuracy:", test_acc)
print("Testing precision:", test_precision)
print("Testing recall:", test_recall)
print("Testing F1 score:", test_f1_score)
print("Testing confusion matrix:")
print(test_conf_matrix)


Training accuracy: 0.9694364851957975
Testing accuracy: 0.7519083969465649
Testing precision: 0.6804123711340206
Testing recall: 0.66
Testing F1 score: 0.6700507614213199
Testing confusion matrix:
[[131  31]
 [ 34  66]]


## Random Forest

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html#sklearn.ensemble.RandomForestRegressor

In [ ]:
from sklearn.ensemble import RandomForestClassifier
###################################################################
#  TODO: Train the Random Forest classifier on the training data  #
###################################################################
rf_clf = RandomForestClassifier(n_estimators=100, random_state=0)
rf_clf.fit(X_train, y_train)

RandomForestClassifier(random_state=0)

### Predict values using trained model

In [ ]:
#####################################################################
# TODO: Predict the output class for the training and test datasets #
#####################################################################

y_train_pred =  rf_clf.predict(X_train)
y_test_pred =  rf_clf.predict(X_test)

### evaluation metrics

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score
#####################################################################
# TODO: Calculate accuracy for training and all metrics for testing #
#####################################################################
train_acc, test_acc, test_precision, test_recall, test_f1_score, test_conf_matrix = [accuracy_score(y_train, y_train_pred),
                                                                                   accuracy_score(y_test, y_test_pred),
                                                                                   precision_score(y_test, y_test_pred),
                                                                                   recall_score(y_test, y_test_pred),
                                                                                   f1_score(y_test, y_test_pred),
                                                                                   confusion_matrix(y_test, y_test_pred)]

print("Training accuracy:", train_acc)
print("Testing accuracy:", test_acc)
print("Testing precision:", test_precision)
print("Testing recall:", test_recall)
print("Testing F1 score:", test_f1_score)
print("Testing confusion matrix:")
print(test_conf_matrix)


Training accuracy: 0.9694364851957975
Testing accuracy: 0.7595419847328244
Testing precision: 0.6989247311827957
Testing recall: 0.65
Testing F1 score: 0.6735751295336787
Testing confusion matrix:
[[134  28]
 [ 35  65]]


### Grid Search for Random Forest

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html

In [ ]:
from sklearn.model_selection import GridSearchCV

#################################################################################################################################################
# TODO: Find the best available parameters (2 parameters for search) for Random Forest classifier using grid search and do the training with it #
#################################################################################################################################################
rfc = RandomForestClassifier(random_state=0)

param_grid = {
    'n_estimators': [50, 200],
    'max_depth': [3, 10]
}

grid_search = GridSearchCV(rfc, param_grid=param_grid, cv=5, n_jobs=-1)

grid_search.fit(X_train, y_train)

print(f"Best parameters: {grid_search.best_params_}")
print(f"Best score: {grid_search.best_score_}")

rfc_best = RandomForestClassifier(**grid_search.best_params_, random_state=42)
rfc_best.fit(X_train, y_train)




Best parameters: {'max_depth': 10, 'n_estimators': 200}
Best score: 0.7392800182273868


RandomForestClassifier(max_depth=10, n_estimators=200, random_state=42)

In [ ]:
#####################################################################
# TODO: Predict the output class for the training and test datasets #
#####################################################################

y_train_pred =  rfc_best.predict(X_train)
y_test_pred =  rfc_best.predict(X_test)

### evaluation metrics

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score
#####################################################################
# TODO: Calculate accuracy for training and all metrics for testing #
#####################################################################
train_acc, test_acc, test_precision, test_recall, test_f1_score, test_conf_matrix = [accuracy_score(y_train, y_train_pred),
                                                                                   accuracy_score(y_test, y_test_pred),
                                                                                   precision_score(y_test, y_test_pred),
                                                                                   recall_score(y_test, y_test_pred),
                                                                                   f1_score(y_test, y_test_pred),
                                                                                   confusion_matrix(y_test, y_test_pred)]

print("Training accuracy:", train_acc)
print("Testing accuracy:", test_acc)
print("Testing precision:", test_precision)
print("Testing recall:", test_recall)
print("Testing F1 score:", test_f1_score)
print("Testing confusion matrix:")
print(test_conf_matrix)


Training accuracy: 0.9694364851957975
Testing accuracy: 0.7595419847328244
Testing precision: 0.6989247311827957
Testing recall: 0.65
Testing F1 score: 0.6735751295336787
Testing confusion matrix:
[[134  28]
 [ 35  65]]


## Gradient Boosting

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingClassifier.html

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
###################################################################
# TODO: Train the Gradient Boost classifier on the training data  #
###################################################################
gb_clf = GradientBoostingClassifier()
gb_clf.fit(X_train, y_train)

GradientBoostingClassifier()

### Predict values using trained model

In [ ]:
#####################################################################
# TODO: Predict the output class for the training and test datasets #
#####################################################################

y_train_pred =  gb_clf.predict(X_train)
y_test_pred =  gb_clf.predict(X_test)

### evaluation metrics

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score
#####################################################################
# TODO: Calculate accuracy for training and all metrics for testing #
#####################################################################
train_acc, test_acc, test_precision, test_recall, test_f1_score, test_conf_matrix = [accuracy_score(y_train, y_train_pred),
                                                                                   accuracy_score(y_test, y_test_pred),
                                                                                   precision_score(y_test, y_test_pred),
                                                                                   recall_score(y_test, y_test_pred),
                                                                                   f1_score(y_test, y_test_pred),
                                                                                   confusion_matrix(y_test, y_test_pred)]

print("Training accuracy:", train_acc)
print("Testing accuracy:", test_acc)
print("Testing precision:", test_precision)
print("Testing recall:", test_recall)
print("Testing F1 score:", test_f1_score)
print("Testing confusion matrix:")
print(test_conf_matrix)


Training accuracy: 0.8729703915950334
Testing accuracy: 0.7709923664122137
Testing precision: 0.7325581395348837
Testing recall: 0.63
Testing F1 score: 0.6774193548387097
Testing confusion matrix:
[[139  23]
 [ 37  63]]


## Ada Boost

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostClassifier.html

In [ ]:
from sklearn.ensemble import AdaBoostClassifier
###################################################################
#    TODO: Train the Ada Boost classifier on the training data    #
###################################################################
ada_clf = AdaBoostClassifier()
ada_clf.fit(X_train, y_train)

AdaBoostClassifier()

### Predict values using trained model

In [ ]:
#####################################################################
# TODO: Predict the output class for the training and test datasets #
#####################################################################

y_train_pred =  ada_clf.predict(X_train)
y_test_pred =  ada_clf.predict(X_test)

### evaluation metrics

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score
#####################################################################
# TODO: Calculate accuracy for training and all metrics for testing #
#####################################################################
train_acc, test_acc, test_precision, test_recall, test_f1_score, test_conf_matrix = [accuracy_score(y_train, y_train_pred),
                                                                                   accuracy_score(y_test, y_test_pred),
                                                                                   precision_score(y_test, y_test_pred),
                                                                                   recall_score(y_test, y_test_pred),
                                                                                   f1_score(y_test, y_test_pred),
                                                                                   confusion_matrix(y_test, y_test_pred)]

print("Training accuracy:", train_acc)
print("Testing accuracy:", test_acc)
print("Testing precision:", test_precision)
print("Testing recall:", test_recall)
print("Testing F1 score:", test_f1_score)
print("Testing confusion matrix:")
print(test_conf_matrix)


Training accuracy: 0.7659980897803247
Testing accuracy: 0.7442748091603053
Testing precision: 0.7037037037037037
Testing recall: 0.57
Testing F1 score: 0.6298342541436465
Testing confusion matrix:
[[138  24]
 [ 43  57]]


## XG Boost

http://xgboost.readthedocs.io/en/latest/

In [ ]:
import xgboost as xgb
###################################################################
#    TODO: Train the XG boost classifier on the training data     #
###################################################################
xgb_clf = xgb.XGBClassifier()
xgb_clf.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

### Predict values using trained model

In [ ]:
#####################################################################
# TODO: Predict the output class for the training and test datasets #
#####################################################################

y_train_pred = xgb_clf.predict(X_train)
y_test_pred = xgb_clf.predict(X_test)

NameError: ignored

### evaluation metrics

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score
#####################################################################
# TODO: Calculate accuracy for training and all metrics for testing #
#####################################################################
train_acc, test_acc, test_precision, test_recall, test_f1_score, test_conf_matrix = [accuracy_score(y_train, y_train_pred),
                                                                                   accuracy_score(y_test, y_test_pred),
                                                                                   precision_score(y_test, y_test_pred),
                                                                                   recall_score(y_test, y_test_pred),
                                                                                   f1_score(y_test, y_test_pred),
                                                                                   confusion_matrix(y_test, y_test_pred)]

print("Training accuracy:", train_acc)
print("Testing accuracy:", test_acc)
print("Testing precision:", test_precision)
print("Testing recall:", test_recall)
print("Testing F1 score:", test_f1_score)
print("Testing confusion matrix:")
print(test_conf_matrix)



Training accuracy: 0.9656160458452722
Testing accuracy: 0.7786259541984732
Testing precision: 0.7386363636363636
Testing recall: 0.65
Testing F1 score: 0.6914893617021277
Testing confusion matrix:
[[139  23]
 [ 35  65]]


### Grid Search for XGBoost

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html

In [ ]:
from sklearn.model_selection import GridSearchCV

###########################################################################################################################################
# TODO: Find the best available parameters (4 parameters for search) for XGboost classifier using grid search and do the training with it #
###########################################################################################################################################
xgb_clf = xgb.XGBClassifier()
param_grid = {
    'learning_rate': [0.02, 0.2, 0.5, 0.15],
    'max_depth': [2, 5, 7, 9],
    'n_estimators': [50, 150, 100],
    'subsample': [0.5, 0.75, 1.0]
}

grid_search = GridSearchCV(xgb_clf, param_grid=param_grid, cv=5, n_jobs=-1)
grid_search.fit(X_train, y_train)
best_params = grid_search.best_params_
xgb_clf_best = xgb.XGBClassifier(**best_params)
xgb_clf_best.fit(X_train, y_train)

print("Best hyperparameters:", best_params)


Best hyperparameters: {'learning_rate': 0.02, 'max_depth': 5, 'n_estimators': 150, 'subsample': 0.5}


### Predict values using trained model

In [ ]:
#####################################################################
# TODO: Predict the output class for the training and test datasets #
#####################################################################

y_train_pred =  xgb_clf_best.predict(X_train)
y_test_pred =  xgb_clf_best.predict(X_test)

### evaluation metrics

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, precision_score, f1_score
#####################################################################
# TODO: Calculate accuracy for training and all metrics for testing #
#####################################################################
train_acc, test_acc, test_precision, test_recall, test_f1_score, test_conf_matrix = [accuracy_score(y_train, y_train_pred),
                                                                                   accuracy_score(y_test, y_test_pred),
                                                                                   precision_score(y_test, y_test_pred),
                                                                                   recall_score(y_test, y_test_pred),
                                                                                   f1_score(y_test, y_test_pred),
                                                                                   confusion_matrix(y_test, y_test_pred)]

print("Training accuracy:", train_acc)
print("Testing accuracy:", test_acc)
print("Testing precision:", test_precision)
print("Testing recall:", test_recall)
print("Testing F1 score:", test_f1_score)
print("Testing confusion matrix:")
print(test_conf_matrix)

Training accuracy: 0.830945558739255
Testing accuracy: 0.7633587786259542
Testing precision: 0.7209302325581395
Testing recall: 0.62
Testing F1 score: 0.6666666666666666
Testing confusion matrix:
[[138  24]
 [ 38  62]]
